### PR TITLE
fix: correct parsing scientific e notation as float

### PR DESCRIPTION
**Pull request by xin-w8023**
This MR should address #12 by simplify change `Loader` from `yaml` to `rumel.yaml`.

### CODE REVIEW

**Comment by xin-w8023** [comment]
For example:
```python3
yaml_str = '''
x: 1e-4
y: !ref <x> * 0.1
'''
loaded_yaml = load_hyperpyyaml(yaml_str)
print(loaded_yaml)
print(type(loaded_yaml["x"]), type(loaded_yaml["y"]))
```
with `yaml.Loader`, the output will be
```text
{'x': '1e-4', 'y': '1e-05'}
<class 'str'> <class 'str'>
```

with  `rumel.yaml.Loader`, the output will be
```text
{'x': 0.0001, 'y': 1e-05}
<class 'float'> <class 'float'>

```

**Comment by xin-w8023** [comment]
@pplantinga hi, could you make a quick review for this MR?

**Comment by pplantinga** [comment]
This is a known issue with pyyaml https://github.com/yaml/pyyaml/issues/173 implementing the 1.1 spec instead of 1.2.  To read these as floats, one could simply use `1.e-4` instead of `1e-4`.

While it would be nice to have this, the approach outlined here fails the tests, and looks to me like it would take some considerable effort to get the tests to pass again, since changing the engine is a significant change. If you're willing to put that work in, more power to you, but this is not a pressing enough issue for us to solve it on our side.

**Comment by xin-w8023** [comment]
> This is a known issue with pyyaml [yaml/pyyaml#173](https://github.com/yaml/pyyaml/issues/173) implementing the 1.1 spec instead of 1.2. To read these as floats, one could simply use `1.e-4` instead of `1e-4`.
> 
> While it would be nice to have this, the approach outlined here fails the tests, and looks to me like it would take some considerable effort to get the tests to pass again, since changing the engine is a significant change. If you're willing to put that work in, more power to you, but this is not a pressing enough issue for us to solve it on our side.

Hi, it seems like the Loader didn't add the constructor. It passed all test offline. Could you approve again to see if it could pass all the tests on CI?

**Pull request merged**
